<article class="importance-<?= $article['importance'] ?>">
    <div>
        <h1><?= $article['title']?></h1>
        <p>Článok napísal: <strong><?= $article['nick']?></strong>, dňa: <span>
                <?php $date = strtotime($article['date_creation']); echo date('d.m.Y', $date); ?></span></p>

        <?php if($article['date_edit'] !== null) { ?>
            <p>Dátum poslednej úpravy: <span><?php $date = strtotime($article['date_edit']); echo date('d.m.Y', $date); ?></span></p>
        <?php } ?>
    </div>
    <div>
        <?php if($article['id_example'] != null) { ?>
            <p class="linkOfImportance"><a href="../../code-play.php?example=<?= $article['id_example'] ?>">Otvoriť príklad</a></p>
        <?php } ?>
    </div>
    <div>
        <?= $article['text'] ?>
    </div>
</article>