<?php if(strpos($_SERVER['REQUEST_URI'], 'admin') !== false) echo "<form method=\"post\" id='aside-article'>" ?>
    <ul id="nav-article">
        <?php foreach ($articleNames as $artic) : ?>
            <li><button <?php if(strpos($_SERVER['REQUEST_URI'], 'admin') !== false) echo "type='submit' name='article'" ?> value="<?=$artic['id_article']?>"><?=$artic['title']?></button></li>
        <?php endforeach ?>
    </ul>
<?php if(strpos($_SERVER['REQUEST_URI'], 'admin') !== false) echo "</form>" ?>