<div id="create-category">
    <h1>Vytvoriť novú kategóriu</h1>
    <form method="post">
        <label>Názov kategórie:
            <input type="text" name="category-name" minlength="3" maxlength="100" placeholder="Web - 2. ročník" required
            value="<?= $categControll->clearPost('category-name') ?>">
        </label>
        <label>Popis kategórie:
            <textarea name="category-desc" minlength="20" maxlength="2000" placeholder="Sem napíšte popis ku kategórii - aké články obsahuje... Môžete používať HTML značky." required><?= $categControll->clearPost('category-desc') ?></textarea>
        </label><!--todo tu je asi zbytocne pouzivat nieco ine nez texareu?-->
        <p>Chcete, aby bola kategória ihneď (aj všetky jej články) viditeľná pre všetkých užívateľov?</p>
        <label><input type="radio" name="category-visibility" value="1">Áno</label>
        <label><input type="radio" name="category-visibility" value="0" checked>Nie</label>
        <input type="submit" value="Vytvoriť kategóriu">
    </form>
</div>