<div id="create-article">
    <h1>Vytvoriť nový článok</h1>
    <form method="post">
        <label>Nadpis článku:
            <input type="text" name="article-title" minlength="3" maxlength="200" placeholder="Formátovanie obrázkov" required
            value="<?= $articControll->clearPost('article-title') ?>">
        </label>
        <label for="article-category">Kategória:</label>
            <?php $categControll->loadCatSelect() ?>
        <label for="article-importance">Zaradenie článku:</label>
        <?php require($_SERVER['DOCUMENT_ROOT']."/wcm/view/importance-select.phtml"); ?>
        <label>Text článku:
            <textarea name="article-text" minlength="50" maxlength="65535" placeholder="Sem napíšte celý Váš článok... Môžete používať HTML značky." required><?= $articControll->clearPost('article-text') ?></textarea>
        </label><!--todo tu pouzijeme nieco pokrocilejsie nez text area?-->
        <input type="submit" value="Pridať článok">
    </form>
</div>