<div id="create-article"><!-- toto sa zobrazi iba prihlasenym -->
    <h1>Vytvoriť nový článok</h1>
    <form method="post">
        <label>Nadpis článku:
            <input type="text" name="article-title" minlength="3" maxlength="200" placeholder="Formátovanie obrázkov" required>
        </label>
        <!--TODO tu bude musiet byt roletka aktualne existujucich kategorii
        <label>Kategória:
            <input type="text" name="article-category" minlength="3" maxlength="100" placeholder="programovanie jazykC" required>
        </label>-->
        <label>Text článku:
            <textarea name="article-text" minlength="50" maxlength="65535" placeholder="Sem napíšte celý Váš článok..." required></textarea>
        </label><!--todo tu pouzijeme nieco pokrocilejsie nez text area?-->
        <input type="submit" value="Pridať článok">
    </form>
</div>