<div id="create-category">
    <h1>Vytvoriť novú kategóriu</h1>
    <form method="post">
        <label>Názov kategórie:
            <input type="text" name="category-name" minlength="3" maxlength="100" placeholder="Web - 2. ročník" required
            value="<?= $categControll->clearPost('category-name') ?>">
        </label>
        <label>Popis kategórie:
            <textarea name="category-desc" minlength="20" maxlength="2000" placeholder="Sem napíšte popis ku kategórii - aké články obsahuje... Môžete používať HTML značky." required>
                <?= $categControll->clearPost('category-desc') ?>
            </textarea>
        </label><!--todo tu je asi zbytocne pouzivat nieco ine nez texareu?-->
        <input type="submit" value="Vytvoriť kategóriu">
        <!--todo viditelnost na zaklikavanie?-->
    </form>
</div>