<div id="edite-article">
    <h1>Upraviť článok: <span><?= $articEdit['title'] ?></span></h1>
    <form method="post">
        <label>Nadpis článku:
            <input type="text" name="edit-article-title" minlength="3" maxlength="200" placeholder="Formátovanie obrázkov" required
                   value="<?= $articEdit['title'] ?>">
        </label>
        <label for="article-category">Zvoľte kategóriu, do ktorej bude článok zaradený:</label>
        <?php require($_SERVER['DOCUMENT_ROOT']."/wcm/view/category-select.phtml"); ?>
        <label>Text článku:
            <textarea name="edit-article-text" minlength="50" maxlength="65535" placeholder="Sem napíšte celý Váš článok... Môžete používať HTML značky." required><?=$articEdit['text']?></textarea>
        </label><!--todo tu pouzijeme nieco pokrocilejsie nez text area?-->
        <input type="submit" value="Upraviť článok">
    </form>
</div>