<div id="login">
    <h1>Administrátorské prihlasovanie</h1>
    <form method="post">
        <label>Nick:
            <input type="text" name="login-nick" minlength="4" maxlength="30" placeholder="Frenky22" required>
        </label>
        <label>Heslo:
            <input type="password" name="login-passwd" minlength="6" maxlength="30" required>
        </label>
        <input type="submit" value="Prihlásiť sa">
    </form>
</div>