<div id="verified-admin">
    <h1>Administrátori čakajúci na schválenie</h1>

        <?php if(!empty($verifAdmin)) { ?>
            <p>Prezrite si E-mailové adresy a na základe nich schvaľujte / zamietajte žiadosti.</p>
            <form method="post">
                <table>
                    <?php foreach ($verifAdmin as $admin) : ?>
                        <tr>
                            <th><?= $admin['nick']?></th>
                            <th><?= $admin['mail']?></th>
                            <th><button type="submit" name="admin-delete" value="<?=$admin['nick']?>">Zamietnuť žiadosť</button></th>
                            <th><button type="submit" name="admin-confirm" value="<?=$admin['nick']?>">Potvrdiť žiadosť</button></th>
                        </tr>
                    <?php endforeach ?>
                </table>
            </form>
        <?php } else { ?>
            <p>Žiadna žiadosť čakajúca na Vaše schválenie!</p>
        <?php } ?>
</div>