<div id="create-css-property">
    <h1>Vytvoriť novú CSS vlastnosť</h1>
    <p>Názov vlastnosti píšte bez <em>:</em> na konci.</p>
    <p>Do políčka hodnoty musíte napísať html kód, nestačia hodnoty. Napríklad pri <i>text-align</i> nestačí napísať <i>left</i>, <i>center</i>, <i>right</i>, ale treba:
        <code>&lt;select&gt;
            &lt;option value="left"&gt;left&lt;/option&gt;
            &lt;option value="center"&gt;center&lt;/option&gt;
            ...
            &lt;/select&gt;</code>
    </p>
    <p>Popis vlastnosti je voliteľný.</p>
    <form method="post">
        <label>Názov vlastnosti:
            <input type="text" name="prop-name" minlength="3" maxlength="50" placeholder="text-align" required
                   value="<?= $cssProp['prop-name'] ?>">
        </label>
        <label>Hodnoty vlastnosti:
            <textarea name="prop-value" minlength="10" maxlength="2000" placeholder="Sem napíšte hodnoty, ktoré môže CSS vlastnosť nadobúdať. Musíte používať HTML značky." required><?= $cssProp['prop-value'] ?></textarea>
        </label>
        <label>Zaradenie vlastnosti:
            <?php require($_SERVER['DOCUMENT_ROOT']."/wcm/view/code-play/css-property-select.phtml"); ?>
        </label>
        <label>Popis vlastnosti:
            <textarea name="prop-description" minlength="20" maxlength="65535" placeholder="Sem napíšte popis CSS vlastnosti. Môžete používať HTML značky."><?= $cssProp['prop-description'] ?></textarea>
        </label>
        <input type="submit" name="create-css-prop" value="Vytvoriť kategóriu">
    </form>
</div>