<div>
    <?php foreach ($cssUse as $use) : ?>
        <form method="post" class="saved">
            <?php require($_SERVER['DOCUMENT_ROOT']."/wcm/view/code-play/css-property-select.phtml") ?>
            <input type="text" name="for-element" minlength="1" maxlength="60" value="<?=$use['for_element']?>" required>
            <button type="submit" name="use-edit" value="<?=$use['id_use']?>">Upraviť</button>
            <button type="submit" name="use-delete" value="<?=$use['id_use']?>">Delete</button>
        </form>
    <?php endforeach ?>

    <?php if(isset($use['id_prop'])) unset($use['id_prop']); ?>

    <form method="post">
        <?php require($_SERVER['DOCUMENT_ROOT']."/wcm/view/code-play/css-property-select.phtml") ?>
        <input type="text" name="for-element" minlength="1" maxlength="60" value="<?php if(isset($_POST['for-element'])) echo $_POST['for-element'] ?>" required>

        <!--kym nebude example vytvoreny, tak nebudeme moct k nemu pridavat vlastnosti-->
        <?php if(isset($_SESSION['example'])) { ?>
            <button type="submit" name="use-save">Uložiť</button>
        <?php } ?>
    </form>
</div>