<?php require($_SERVER['DOCUMENT_ROOT']."/wcm/view/code-play/example-ul.phtml") ?>
<div>
    <p>Odporúčaný postup pri vytváraní príkladu:</p>
    <ol>
        <li>Najskôr napíšte HTML kód príkladu</li>
        <li>Príklad uložte</li>
        <li>Zvoľte požadovanú CSS vlastnosť a napíšte selektor z Vášho HTML kódu, na ktorý sa bude táto vlastnosť aplikovať</li>
        <li>Stlačte tlačidlo <i>Uložiť</i> - ak pozadie danej vlastnosti zozelenalo, znamená to, že vlastnosť bola úspešne uložená</li>
        <li>Opakujte body 3 a 4, kým nenavolíte všetky vlastnosti - <em>Príklad už nemusíte ukladať</em></li>
    </ol>
    <p>Všetky príklady sa zobrazia všetkým užívateľom.</p>
    <form method="post">
        <ul>
            <li><button type="submit" name="subpage" value="example-form">Vytvoriť nový príklad</button></li>
        </ul>
    </form>
</div>