<?php require($_SERVER['DOCUMENT_ROOT']."/wcm/view/code-play/css-use-menu.phtml") ?>
<div>
    <h1><?php if($example['exam_name'] != "") { echo "Príklad: <span>{$example['exam_name']}</span>"; } else echo "Nový príklad" ?></h1>
    <form method="post">
        <label>Názov príkladu:
            <input type="text" name="example-name" minlength="3" maxlength="60" placeholder="Tabuľky" required
                   value="<?= $example['exam_name'] ?>">
        </label>
        <label>Popis celého príkladu (voliteľný):
            <textarea name="example-description" minlength="20" maxlength="1000" placeholder="Sem môžete napísať krátky popis (max. 1000 znakov) príkladu. Nepoužívajte HTML značky."><?=$example['exam_description']?></textarea>
        </label>
        <label>HTML kód:
            <textarea name="example-code" minlength="10" maxlength="3000" placeholder="<h1>Nadpis</h1><p>Popis...</p>"><?=$example['exam_code']?></textarea>
        </label>
        <label>JS kód/jQuery kód (voliteľný):
            <textarea name="example-js" minlength="30" maxlength="4000" placeholder="window.onload = function() { ... };"><?=$example['exam_js']?></textarea>
        </label>
        <label>Popis JS/jQuery kódu (voliteľný):
            <textarea class="tinyEditor" name="example-js-desc" minlength="20" maxlength="65535" placeholder="Sem napíšte popis JS kódu. HTML značky sú povolené."><?=$example['exam_js_description']?></textarea>
        </label>

        <?php if(isset($_SESSION['example'])) { ?>
            <input type="submit" name="edit-example" value="Uložiť zmeny">
        <?php } else { ?>
            <input type="submit" name="create-example" value="Vytvoriť príklad">
        <?php } ?>
    </form>

    <?php if(isset($_SESSION['example'])) { ?>
        <form method="post">
            <div class="delete">
                <p>Pozor, nasledujúca akcia je nezvratná! Odkazy na tento príklad budú vymazané aj zo všetkých článkov!</p>
                <input type="submit" name="delete-example" value="Zmazať príklad">
            </div>
        </form>
    <?php } ?>
</div>