<?php require($_SERVER['DOCUMENT_ROOT']."/wcm/view/code-play/example-ul.phtml") ?>
<div>
    <p>Odporúčaný postup pri vytváraní príkladu:</p>
    <ol>
        <li>Najskôr napíšte HTML kód príkladu</li>
        <li>Príklad uložte</li>
        <li>Zvoľte požadovanú CSS vlastnosť a napíšte selektor z Vášho HTML kódu, na ktorý sa bude táto vlastnosť aplikovať</li>
        <li>Stlačte tlačidlo <i>Uložiť</i> - ak pozadie danej vlastnosti zozelenalo, znamená to, že vlastnosť bola úspešne uložená</li>
        <li>Opakujte body 3 a 4, kým nenavolíte všetky vlastnosti - <em>Príklad už nemusíte ukladať</em></li>
        <li>K HTML kódu napíšte zodpovedajúci JavaScript-ový kód s popisom - <em>Príklad musíte uložiť</em></li>
    </ol>

    <p>HTML kód príkladu môže obsahovať ľubovoľné HTML tagy</p>
    <p>Nemusíte vybrať ani jednu CSS vlastnosť</p>
    <p>Selektor pri CSS vlastnostiach môže byť ľubovoľný, napríklad: <code>main > div p</code></p>
    <p>Kód v JavaScript-e môže byť napísaný aj v knižnici jQuery</p>

    <p><em>Všetky príklady sa zobrazia všetkým užívateľom.</em></p>
    <form method="post">
        <ul>
            <li><button type="submit" name="subpage" value="example-form">Vytvoriť nový príklad</button></li>
        </ul>
    </form>
</div>