<?php if(strpos($_SERVER['REQUEST_URI'], 'admin') !== false) echo "<form method=\"post\">" ?>
    <ul>
        <?php foreach ($examples as $example) : ?>
            <li><button <?php if(strpos($_SERVER['REQUEST_URI'], 'admin') !== false) echo "type='submit' name='example'" ?> value="<?=$example['id_example']?>"><?=$example['exam_name']?></button></li>
        <?php endforeach ?>
    </ul>
<?php if(strpos($_SERVER['REQUEST_URI'], 'admin') !== false) echo "</form>" ?>