<?php require($_SERVER['DOCUMENT_ROOT']."/wcm/view/code-play/example-ul.phtml") ?>
<div>
    <p>Odporúčaný postup pri vytváraní príkladu:</p>
    <ol><!-- todo urcite sa pozriet na toto ci to sedi s tym ako som to nakoniec urobil -->
        <li>Najskôr napíšte HTML kód príkladu</li>
        <li>Kliknutím na požadovanú CSS vlastnosť ju vyberiete</li>
        <li>Zadajte selektor, ktorý určí, na ktorý element z HTML kódu sa bude táto vlastnosť aplikovať</li>
    </ol>
    <p>Všetky príklady sa zobrazia všetkým užívateľom.</p>
    <form method="post">
        <ul>
            <li><button type="submit" name="new-example">Vytvoriť nový príklad</button></li>
        </ul>
    </form>
</div>